/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package thesimpleems_16nov;

/**
 *
 * @author mewtwoswift
 */
public class NewEmployee extends javax.swing.JFrame {
    
    private MyHashTable theHT;
    /** Creates new form DisplayEmployee */
    public NewEmployee(MyHashTable ht) {
        initComponents();
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        resetAllFields();
        theHT = ht;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        genderDropdown = new javax.swing.JComboBox<>();
        deductRateSlider = new javax.swing.JSlider();
        deductRateField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        parttimeRadio = new javax.swing.JRadioButton();
        fulltimeRadio = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        customPanel = new javax.swing.JPanel();
        empTypeLabel = new javax.swing.JLabel();
        salaryLabel = new javax.swing.JLabel();
        salaryField = new javax.swing.JTextField();
        hpwLabel = new javax.swing.JLabel();
        hpwField = new javax.swing.JTextField();
        wpyLabel = new javax.swing.JLabel();
        wpyField = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        outDialog = new javax.swing.JLabel();
        locationDropdown = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("New Employee");

        jLabel2.setText("ID");

        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("First Name");

        jLabel4.setText("Last Name");

        jLabel5.setText("Gender");

        jLabel6.setText("Location");

        jLabel7.setText("Deduct Rate");

        genderDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --", "Male", "Female", "Other" }));
        genderDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderDropdownActionPerformed(evt);
            }
        });

        deductRateSlider.setValue(0);
        deductRateSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                deductRateSliderStateChanged(evt);
            }
        });

        deductRateField.setText("0");
        deductRateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deductRateFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("%");

        buttonGroup1.add(parttimeRadio);
        parttimeRadio.setText("Part Time");
        parttimeRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parttimeRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(fulltimeRadio);
        fulltimeRadio.setText("Full-Time");
        fulltimeRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fulltimeRadioActionPerformed(evt);
            }
        });

        jLabel9.setText("Type");

        customPanel.setBackground(new java.awt.Color(220, 220, 220));

        empTypeLabel.setText("Full-Time");

        salaryLabel.setText("Annual Salary");

        hpwLabel.setText("Hours / Week ");

        hpwField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hpwFieldActionPerformed(evt);
            }
        });

        wpyLabel.setText("Weeks / Year");

        javax.swing.GroupLayout customPanelLayout = new javax.swing.GroupLayout(customPanel);
        customPanel.setLayout(customPanelLayout);
        customPanelLayout.setHorizontalGroup(
            customPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customPanelLayout.createSequentialGroup()
                        .addComponent(empTypeLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customPanelLayout.createSequentialGroup()
                        .addGroup(customPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(customPanelLayout.createSequentialGroup()
                                .addComponent(salaryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                .addGap(12, 12, 12))
                            .addComponent(hpwLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(wpyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(customPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(wpyField)
                            .addComponent(hpwField)
                            .addComponent(salaryField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        customPanelLayout.setVerticalGroup(
            customPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(empTypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salaryLabel)
                    .addComponent(salaryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hpwLabel)
                    .addComponent(hpwField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wpyLabel)
                    .addComponent(wpyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        deleteButton.setText("Create");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        locationDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --", "Brantford", "Brampton", "Guelph", "Hamilton", "Kitchener", "Mississauga", "Oakville", "Oshawa", "Toronto", "Vaughan", " ", " ", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(idField, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(lastNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(genderDropdown, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(deductRateSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(deductRateField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel8))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(fulltimeRadio)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(parttimeRadio)))
                            .addComponent(locationDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(customPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(genderDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(locationDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(deductRateSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deductRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(parttimeRadio)
                            .addComponent(fulltimeRadio)
                            .addComponent(jLabel9)))
                    .addComponent(customPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(outDialog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteButton)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void genderDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderDropdownActionPerformed

    private void parttimeRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parttimeRadioActionPerformed
        empTypeLabel.setText("Part-Time");
        salaryLabel.setText("Hourly");
        salaryField.setText("");
        enableRequired();
        hpwLabel.setVisible(true);
        hpwField.setVisible(true);
        wpyLabel.setVisible(true);
        wpyField.setVisible(true);
    }//GEN-LAST:event_parttimeRadioActionPerformed

    private void hpwFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpwFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hpwFieldActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int id;
        try {
            id = Integer.parseInt(idField.getText());
        } catch (NumberFormatException e) {
            outDialog.setText(String.format("Error in employee parameters - %s cannot be converted to an integer", e.getMessage()));
            return;
        }
        String firstname = firstNameField.getText();
        String lastname = lastNameField.getText();
        int gender = genderDropdown.getSelectedIndex();
        int workloc = locationDropdown.getSelectedIndex();
        if (gender == 0) {
            outDialog.setText("Error - Gender is a required parameter");
            return;
        }
        if (workloc == 0) {
            outDialog.setText("Error - Location is a required parameter");
            return;
        }
        
        double deductRate = Double.parseDouble(deductRateField.getText())/100d;
                
        if (parttimeRadio.isSelected()) {
            double hourly, hpw, wpy;
            try {
                hourly = Double.parseDouble(salaryField.getText());
                hpw = Double.parseDouble(hpwField.getText());
                wpy = Double.parseDouble(wpyField.getText());
            } catch (NumberFormatException e) {
                outDialog.setText(String.format("Error in Part-Time parameters - %s cannot be converted to a number", e.getMessage()));
                return;
            }
            theHT.addEmployee(new PTE(id, firstname, lastname, gender, workloc, deductRate, hourly, hpw, wpy));
            resetAllFields();
            outDialog.setText(String.format("Successfully added %s %s to the database.", firstname, lastname));
        } else if (fulltimeRadio.isSelected()) {
            double annualsal;
            try {
                annualsal = Double.parseDouble(salaryField.getText());
            } catch (NumberFormatException e) {
                outDialog.setText(String.format("Error in Full-Time parameters - %s cannot be converted to a number", e.getMessage()));
                return;
            }
            theHT.addEmployee(new FTE(id, firstname, lastname, gender, workloc, deductRate, annualsal));
            resetAllFields();
            outDialog.setText(String.format("Successfully added %s %s to the database.", firstname, lastname));
        } else {
            outDialog.setText("Error - Employee must be Part-time or Full-time.");
            return;
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void fulltimeRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fulltimeRadioActionPerformed
        empTypeLabel.setText("Full-Time");
        salaryLabel.setText("Annual Salary");
        salaryField.setText("");
        enableRequired();
        hpwLabel.setVisible(false);
        hpwField.setVisible(false);
        wpyLabel.setVisible(false);
        wpyField.setVisible(false);  
    }//GEN-LAST:event_fulltimeRadioActionPerformed

    private void deductRateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deductRateFieldActionPerformed
        int value;
        try { 
            value = Integer.parseInt(evt.getActionCommand());
        } catch (NumberFormatException e) {
            outDialog.setText("Deduction rate percentage must be a number.");
            value = 0;
        }
        deductRateSlider.setValue(value);
    }//GEN-LAST:event_deductRateFieldActionPerformed

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void deductRateSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_deductRateSliderStateChanged
        int value = deductRateSlider.getValue();
        deductRateField.setText(Integer.toString(value));
    }//GEN-LAST:event_deductRateSliderStateChanged
    
    private void enableRequired() {
        customPanel.setVisible(true);
        salaryLabel.setVisible(true);
        salaryField.setVisible(true);
        empTypeLabel.setVisible(true);
    }
    
    private void resetAllFields() {
        deductRateField.setText("0");
        deductRateSlider.setValue(0);
        idField.setText("");
        lastNameField.setText("");
        firstNameField.setText("");
        genderDropdown.setSelectedIndex(0);
        locationDropdown.setSelectedIndex(0);
        parttimeRadio.setSelected(false);
        fulltimeRadio.setSelected(false);
        customPanel.setVisible(false);
        salaryLabel.setVisible(false);
        salaryField.setVisible(false);
        empTypeLabel.setVisible(false);
        hpwLabel.setVisible(false);
        hpwField.setVisible(false);
        wpyLabel.setVisible(false);
        wpyField.setVisible(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel customPanel;
    private javax.swing.JTextField deductRateField;
    private javax.swing.JSlider deductRateSlider;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel empTypeLabel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JRadioButton fulltimeRadio;
    private javax.swing.JComboBox<String> genderDropdown;
    private javax.swing.JTextField hpwField;
    private javax.swing.JLabel hpwLabel;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JComboBox<String> locationDropdown;
    private javax.swing.JLabel outDialog;
    private javax.swing.JRadioButton parttimeRadio;
    private javax.swing.JTextField salaryField;
    private javax.swing.JLabel salaryLabel;
    private javax.swing.JTextField wpyField;
    private javax.swing.JLabel wpyLabel;
    // End of variables declaration//GEN-END:variables

}
